version: "3"

services:
  api:
    build: .
    command: /bin/sh docker-start.sh
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    depends_on:
      - database_dev
    links:
      - database_dev

  database_dev:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"